### ISSUE TITLE
Update intervals?

### ISSUE THREAD

**Issue by thisIsMikeKane** [bm1549/home-assistant-frigidaire#1]
I'm working on improving the reliability and fidelity of the `current_temperature` readings. It updates very infrequently, perhaps only when settings are changed? I'm having a difficult time finding if/where a regular polling interval is set. What is throwing me off I think is this comment

```python
        # Although we can access the Frigidaire API to get updates, they are
        # not reflected immediately after making a request. To improve the UX
        # around this, we set assume_state to True
        self._attr_assumed_state = True
```

Does this mean the state is not regularly updated? Or, is it just that the state read back after changing a state is ignored and not updated until the regular polling interval? 

Thank you for helping clarify. I'd be happy to help improve this code.

**Comment by bm1549** [comment]
First off, thank you for being a contributor!

> I'm having a difficult time finding if/where a regular polling interval is set

I'm no expert at home assistant, but I *think* it's updated [every 30 seconds](https://www.home-assistant.io/docs/configuration/platform_options/) by default, but you can configure it to be more frequent in your own setup

> Does this mean the state is not regularly updated? Or, is it just that the state read back after changing a state is ignored and not updated until the regular polling interval?

It's closer to the latter, but the situation is actually a bit more frustrating. When developing this component, I noticed that Frigidaire didn't update its current temperature state immediately after issuing a request. To make it "seem" like it's updated each time, I set that config value on the component level so that users of the component don't need to manually update their config files. To best illustrate the problem, I'll include a pseudocode snippet below
```python
get_temperature() # returns 72
set_temperature(70) # returns success
get_temperature() # returns 72
# wait a few seconds
get_temperature() # returns 70
```

**Comment by karlg100** [comment]
Just to comment on this, because I was struggling with this as well.  I've used automation rules so that my EcoBee can control the Frigidaire window units to save $$ on electricity. But the refresh interval is annoying and causes a lot of delays in the whole setup.

I found there's no great way to change the polling interval globally or for a specific integration. I believe this integration could be tweaked to make this a tunable option, however, requiring some code changes and a lot of testing.

The workaround quickfix I found without changing code is to use an automation and the homeassistant.update_entity service. I added a time pattern automation to fire every 5 seconds and call homeassistant.update_entity for the specific entity I want updated more frequently. 

Below is a YAML example for mine to update every 5 seconds for one specific entity. (climate.family_room is a window AC unit in the Family Room) You should be able to just copy paste this into the YAML editor for a new automation.

```
alias: Update Family Room Climate
description: ""
trigger:
  - platform: time_pattern
    seconds: /5
condition: []
action:
  - service: homeassistant.update_entity
    data: {}
    target:
      entity_id: climate.family_room
mode: single
```
