### ISSUE TITLE
Cannot synchronize celsius on HA with celsius on the AC unit

### ISSUE THREAD

**Issue by amaisano** [bm1549/home-assistant-frigidaire#56]
This is really bizarre:

I have HA units configured globally to C. I also have the Frigidaire 2.0 app global (affects all units) measurement to C.

However, when the F2.0 app is set to C, HA shows 77C whenever I attempt to change the target temp on HA - it's putting "C" on but that number is 100% an F number.

If I set the F2.0 app to use F as the measurement, HA properly shows 22C and setting things through HA uses correct C units, BUT the AC unit in the window switches to showing 77F units!?!?!

Someone please help us figure out this celsius stuff once and for all - it's been buggy for years.

**Comment by amaisano** [comment]
Oh one last thing: if I'm stuck where the AC unit LED display says 77F and HA says 22C, if I press the - and + buttons on the AC unit at the same time and hold to switch the units back to C on the AC Unit display, it instantly changes HA back to 77C (incorrect).

So my workaround right now is to set HA to C, F2.0 app to F, and deal with the physical AC units being controlled in F, and HA in C. It's horrible.

**Comment by casebeer** [comment]
I believe this issue is not completely solved by #63. The set_temperature() method in the Frigidaire client library assumes its argument is in Fahrenheit, but this HA component provides the target temperature in whatever units are configured in Home Assistant, without any conversions. 

#63 fixes this mismatch in the *read* case by reading the target temperature matching our temperature_unit config, but the issue still remains for the *write* case. #68 makes the analogous write-case fix to #63, but relies on https://github.com/bm1549/frigidaire/pull/37 to expose the underling Celsius- and Fahrenheit-specific target temperature setting actions.

**Comment by amaisano** [comment]
Hallelujah! THANK YOU
