### ISSUE TITLE
Setting Temperature when in Celsius mode does not work correctly

### ISSUE THREAD

**Issue by WillThompson** [bm1549/home-assistant-frigidaire#65]
There appear to be some issues reading the temperature of the air conditioner using the thermostat card in home assistant. The temperature conversions between Fahrenheit and celsius do not seem to be performed properly when the temperature is changed nor returned to the user via the thermostat card.

![Screenshot 2024-08-08 at 13-12-41 Main – Home Assistant](https://github.com/user-attachments/assets/3ad55716-efe3-4583-b7f2-5f44756ea1f5)

The sensor is reading the room as 71.6C, clearly not correct (but 71.6F sounds reasonable).

I think when setting the temperature or reading the temparature, there is a missing conversion step if the user has set celsuis as their default?

(btw, thank you for the integration. I appreciate your work on it)

**Comment by WillThompson** [comment]
As another user mentioned [here](https://github.com/bm1549/home-assistant-frigidaire/issues/56#issue-2324326248), it is possible to set the temperature unit of the air conditioner to Fahrenheit, which fixes the problem, but then your interactions with the hardware itself have to be done in Fahrenheit. Not ideal, but I guess I can live with that...

**Comment by casebeer** [comment]
I can confirm this bug report. The ambient temperature is read from the Frigidaire API in degrees F and reported back regardless of what the custom component's temperature unit is set to. 

This means if the component's unit is degrees Celsius, it'll request the ambient temperature in degrees Fahrenheit and report it as degrees Celsius with no conversion. This should be fixed by Pull #67
